% Function autogenerated by MATLAB import functionality
function DataSummaryForCoursework = import_times(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  DATASUMMARYFORCOURSEWORK = IMPORTFILE1(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  DATASUMMARYFORCOURSEWORK = IMPORTFILE1(FILE, SHEET) reads from the
%  specified worksheet.
%
%  DATASUMMARYFORCOURSEWORK = IMPORTFILE1(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DataSummaryForCoursework = importfile1("/Users/Martin/Desktop/cw2/DataSummaryForCoursework.xlsx", "PB-GRP4-SESS2-Trial2", [5, 9]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Apr-2022 23:27:27

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [5, 9];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "D" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = "VarName4";
opts.VariableTypes = "double";

% Import the data
DataSummaryForCoursework = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "D" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    DataSummaryForCoursework = [DataSummaryForCoursework; tb]; %#ok<AGROW>
end

end