% Function autogenerated by MATLAB import functionality
function DataSummaryForCoursework = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  DATASUMMARYFORCOURSEWORK = IMPORTFILE1(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  DATASUMMARYFORCOURSEWORK = IMPORTFILE1(FILE, SHEET) reads from the
%  specified worksheet.
%
%  DATASUMMARYFORCOURSEWORK = IMPORTFILE1(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DataSummaryForCoursework = importfile1("/Users/Martin/Desktop/cw2/DataSummaryForCoursework.xlsx", "PB-GRP4-SESS2-Trial2", [16, 140]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-May-2022 00:53:58

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [16, 140];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 14);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":N" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "PatientBLAnkleAngles", "VarName4", "VarName5", "PatientBLHipAngles", "VarName7", "VarName8", "PatientBLKneeAngles", "VarName10", "VarName11", "PatientBLPelvisAngles", "VarName13", "VarName14"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
DataSummaryForCoursework = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":N" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    DataSummaryForCoursework = [DataSummaryForCoursework; tb]; %#ok<AGROW>
end

end